# Generated by Django 3.1.6 on 2021-08-21 18:25

from django.db import migrations, models
import django.db.models.deletion
import reseau_artistes_app.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.IntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Image'), (4, 'Book')])),
                ('description', models.CharField(max_length=100)),
                ('content', models.FileField(storage=reseau_artistes_app.storage.InterPlanetaryFileSystemStorage(), upload_to='')),
                ('last_modified_at', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(default=None, related_name='likes', to='reseau_artistes_app.Artist')),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='reseau_artistes_app.artist')),
                ('saves', models.ManyToManyField(default=None, related_name='saves', to='reseau_artistes_app.Artist')),
                ('views', models.ManyToManyField(default=None, related_name='views', to='reseau_artistes_app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='reseau_artistes_app.artist')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='reseau_artistes_app.post')),
            ],
        ),
    ]
