# Generated by Django 3.1.6 on 2021-08-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseau_artistes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
